#include "arduino_secrets.h"
// Timer - Version: Latest 


/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/62b3541b-9578-4c22-bf52-1e61e9bb9464 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float sensorValue;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#define buzzerPin 0 
#define GreenLed 14 
#define RedLed 12 
 


#define MQ2pin (A0)

int n,m;
void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
   Serial.println("Gas sensor warming up!");
  delay(5000);
 pinMode(GreenLed, OUTPUT);
  pinMode(RedLed, OUTPUT);
  pinMode(12,OUTPUT);
  pinMode(16,OUTPUT);
  pinMode(buzzerPin,OUTPUT);
  digitalWrite(GreenLed, LOW);
  digitalWrite(RedLed, LOW);
  
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
   sensorValue_READ();
  
}


/*
  Since GasData is READ_WRITE variable, onGasDataChange() is
  executed every time a new value is received from IoT Cloud.
*/

 
  void sensorValue_READ(){
     ArduinoCloud.update();
  sensorValue = analogRead(MQ2pin); 
  
  Serial.println("");
  Serial.print("Sensor Value: ");
  Serial.print(sensorValue);
  Serial.println("");
  
  
  if(sensorValue > 300 && sensorValue < 600)
  {
    Serial.print("Smoke detected!");
  }
  
  
  n=analogRead(A0);

  if(n>600)
  {
  
    n==m;
    m=analogRead(A0);
    Serial.println(m);
    
  }
  if(n>300 && n<600)
  {
    digitalWrite(D3,LOW);
    digitalWrite(D6,HIGH); 
    digitalWrite(D5,LOW);
    tone(buzzerPin,800,80);
    delay(2000);  
  }
  
  if(n<300)
  {
      digitalWrite(D5,HIGH );
      digitalWrite(D3,LOW);
      digitalWrite(D6,LOW);
      delay(2000);
      noTone(buzzerPin);
  }
  }




