#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/98dab5a3-a34d-4c2f-a521-cd3211bd25f9 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool v0;
  bool v1;
  bool v2;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#define RED D6
#define GREEN D7
#define BLUE D8
void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
pinMode(RED, OUTPUT);
  pinMode(GREEN, OUTPUT);
  pinMode(BLUE, OUTPUT);
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  onV0Change();
  onV1Change();
  onV2Change();
  
}



/*
  Since V0 is READ_WRITE variable, onV0Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onV0Change()  {
  if(v0 == 1){
  digitalWrite(RED,LOW);
  }
  else
  {
    digitalWrite(RED,HIGH);
  }
}

/*
  Since V1 is READ_WRITE variable, onV1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onV1Change()  {
  if(v1 == 1){
  digitalWrite(GREEN,LOW);
  }
  else
  {
    digitalWrite(GREEN,HIGH);
  }
}

/*
  Since V2 is READ_WRITE variable, onV2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onV2Change()  {
 if(v2 == 1){
  digitalWrite(BLUE,LOW);
  }
  else
  {
    digitalWrite(BLUE,HIGH);
  }
}


