// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "c2cd3cb3-2397-49f1-af3c-a4b109b91665";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onV0Change();
void onV1Change();
void onV2Change();

bool v0;
bool v1;
bool v2;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(v0, READWRITE, ON_CHANGE, onV0Change);
  ArduinoCloud.addProperty(v1, READWRITE, ON_CHANGE, onV1Change);
  ArduinoCloud.addProperty(v2, READWRITE, ON_CHANGE, onV2Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
