#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/532295c2-b8c2-4f44-990d-e92a4f8d0939 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float nemdegeri;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
int nemPin = A0;
#define relay1 D0



int nemEsikdegeri = 550;

void setup() {
  // Initialize serial and wait for port to open:
  pinMode(nemPin, INPUT);
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
pinMode(relay1, OUTPUT);
digitalWrite(relay1, HIGH);
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  nemdegeri_READ();
  
  
}
void nemdegeri_READ()
{
  nemdegeri = analogRead(nemPin);

  Serial.print("Direnç Değeri: ");
  Serial.println(nemdegeri);

  if(nemdegeri < nemEsikdegeri)
  {
      Serial.println("Ortam ISLAK SULAMA GEREKMİYOR");
   
    digitalWrite(relay1, LOW);
    
  }
  else
  {
    Serial.println("Ortam KURU SULAMA YAPILMASI GEREK");
   digitalWrite(relay1, LOW);
   }
 delay(1000);
  
}

